### ISSUE TITLE
no name is shown inside chat

### ISSUE THREAD

**Issue by Ayoub-Amzouar** [Zqadiri/ft_transcendence#3]
users' username are not shown anymore inside the chat.
@sickl8 @sbensarg 
<img width="798" alt="Screen Shot 2022-10-01 at 3 32 22 PM" src="https://user-images.githubusercontent.com/29388503/193414475-ce2a3bd1-c0de-46e3-9b0d-adc8a07db88c.png">

**Comment by sickl8** [comment]
fixed
